/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package juan.marin.lopez.estadisticasnba;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMINISTRADORGS2
 */
public class EstadisticasNBA extends javax.swing.JPanel {

    /**
     * Creates new form InterfazEstadisticasNBA
     */
    public EstadisticasNBA() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LabelNombreJugador = new javax.swing.JLabel();
        TextNombreJugador = new javax.swing.JTextField();
        Label2Lanzados = new javax.swing.JLabel();
        Label2Encestados = new javax.swing.JLabel();
        SpinnerTotales2 = new javax.swing.JSpinner();
        Spinner2Encestados = new javax.swing.JSpinner();
        Label3Totales = new javax.swing.JLabel();
        SpinnerTotales3 = new javax.swing.JSpinner();
        Label3Encestados = new javax.swing.JLabel();
        Spinner3Encestados = new javax.swing.JSpinner();
        ButtonGuardar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        LabelNombreJugador.setText("Nombre Jugador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(LabelNombreJugador, gridBagConstraints);

        TextNombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreJugadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(TextNombreJugador, gridBagConstraints);

        Label2Lanzados.setText("Tiros de 2 lanzados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(Label2Lanzados, gridBagConstraints);

        Label2Encestados.setText("Tiros de 2 encestados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(Label2Encestados, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(SpinnerTotales2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(Spinner2Encestados, gridBagConstraints);

        Label3Totales.setText("Tiros de 3 lanzados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(Label3Totales, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(SpinnerTotales3, gridBagConstraints);

        Label3Encestados.setText("Tiros de 3 encestados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(Label3Encestados, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 30, 30);
        add(Spinner3Encestados, gridBagConstraints);

        ButtonGuardar.setText("Guardar");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        add(ButtonGuardar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreJugadorActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        // TODO add your handling code here:
        
        String nombreJugador = TextNombreJugador.getText();
        int tiros2Realizados = (Integer) SpinnerTotales2.getValue();
        int tiros2Encestados = (Integer) Spinner2Encestados.getValue();
        int tiros3Realizados = (Integer) SpinnerTotales3.getValue();
        int tiros3Encestados = (Integer) Spinner3Encestados.getValue();
        
        // Calcular los puntos
        int puntos = (2 * tiros2Encestados) + (3 * tiros3Encestados);

        // Calcular FGA
        int fga = tiros2Realizados + tiros3Realizados;

        // Calcular FG% (Field Goal Percentage)
        double fg = (fga > 0) ? (double)(tiros2Encestados + tiros3Encestados) / fga * 100 : 0;

        // Calcular eFG% (Effective Field Goal Percentage)
        double efg = (fga > 0) ? (double)(tiros2Encestados + (0.5 * tiros3Encestados)) / fga * 100 : 0;
        
        int tirosTotalesRealizados = tiros2Realizados + tiros3Realizados;
        int tirosTotalesEncestados = tiros2Encestados + tiros3Encestados;
        
        
        try {
        // Cargar archivo Excel existente, o crear uno si no existe
            File archivo = new File("EstadisticasNBA.xlsx");
            Workbook wb;
            Sheet sheet;

            if (archivo.exists()) {
                // Si el archivo existe, abrirlo
                FileInputStream fis = new FileInputStream(archivo);
                wb = new XSSFWorkbook(fis);
                sheet = wb.getSheetAt(0);
                fis.close();
            } else {
                // Si no existe, crearlo desde cero
                wb = new XSSFWorkbook();
                sheet = wb.createSheet("Estadísticas");

                // Crear las cabeceras (agregar FG%, eFG%, Tiros Totales)
                Row cabecera = sheet.createRow(0);
                cabecera.createCell(0).setCellValue("Nombre Jugador");
                cabecera.createCell(1).setCellValue("Tiros Totales Realizados");
                cabecera.createCell(2).setCellValue("Tiros 2 Realizados");
                cabecera.createCell(3).setCellValue("Tiros 2 Encestados");
                cabecera.createCell(4).setCellValue("Tiros 3 Realizados");
                cabecera.createCell(5).setCellValue("Tiros 3 Encestados");
                cabecera.createCell(6).setCellValue("Tiros Totales Encestados");
                cabecera.createCell(7).setCellValue("% FG");
                cabecera.createCell(8).setCellValue("% eFG");
            }
            
            int rowCount = sheet.getPhysicalNumberOfRows();
                // Crear una nueva fila para el nuevo jugador en la primera fila libre
                Row row = sheet.createRow(rowCount);
                row.createCell(0).setCellValue(nombreJugador);
                row.createCell(1).setCellValue(tirosTotalesRealizados);  // Agregar Tiros Totales Realizados
                row.createCell(2).setCellValue(tiros2Realizados);
                row.createCell(3).setCellValue(tiros2Encestados);
                row.createCell(4).setCellValue(tiros3Realizados);
                row.createCell(5).setCellValue(tiros3Encestados);
                row.createCell(6).setCellValue(tirosTotalesEncestados);  // Agregar Tiros Totales Encestados
                row.createCell(7).setCellValue(fg);  // Agregar % FG al archivo
                row.createCell(8).setCellValue(efg);  // Agregar % eFG al archivo
            
            FileOutputStream fos = new FileOutputStream(archivo);
            wb.write(fos);
            fos.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    public static void main(String args[]) {
        JFrame interfaz = new JFrame("Interfaz");
        EstadisticasNBA panel = new EstadisticasNBA();
        interfaz.setContentPane(panel);
        interfaz.setSize(383, 463);
        interfaz.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        interfaz.setLocationRelativeTo(null);
        interfaz.setVisible(true);
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JLabel Label2Encestados;
    private javax.swing.JLabel Label2Lanzados;
    private javax.swing.JLabel Label3Encestados;
    private javax.swing.JLabel Label3Totales;
    private javax.swing.JLabel LabelNombreJugador;
    private javax.swing.JSpinner Spinner2Encestados;
    private javax.swing.JSpinner Spinner3Encestados;
    private javax.swing.JSpinner SpinnerTotales2;
    private javax.swing.JSpinner SpinnerTotales3;
    private javax.swing.JTextField TextNombreJugador;
    // End of variables declaration//GEN-END:variables
}
